services:
  rabbitMQ:
    image: rabbitmq:3.9.29-management-alpine
    environment:
      #RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASS}
    volumes:
      - ./rabbitMQ/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitMQ/ssl:/etc/ssl
    ports:
      - 5671:5671
      - 15671:15671
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    restart: always
  dashboard-api:
    build:
      context: .
      dockerfile: ./dashboard-api/Dockerfile
    depends_on:
      - rabbitMQ
    environment:
      AMQP_URL: guest:${RABBIT_PASS}@rabbitMQ:5671
      CA_CERT: '/ssl/ca-cert.pem'
      CLIENT_CERT: '/ssl/client-cert.pem'
      CLIENT_KEY: '/ssl/client-key.pem'
      DOMAIN: ${DOMAIN}
      DASHBOARD_PASS: ${DASHBOARD_PASS}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
    volumes:
      - ./sqlite:/sqlite
      - ./dashboard/dist:/dist
      - ./dashboard-api/ssl:/ssl
      - ./grabber/momo-service.zip:/momo-service.zip
    ports:
      - 8844:8844
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    restart: unless-stopped