{
 "title": "Momo Dockers",
 "description": "https://github.com/krol44/momo - more info",
 "tags": [ "docker" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values({__name__=~\"momo_container.*\"},server)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"momo_container.*\", server=~\"$server\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(momo_container_cpu_usage_seconds_total{server=~\"$server\",name=~\"$container\",name=~\".+\"}[5m])) by (server, name) *100",
     "legendFormat": "{{name}} – {{server}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(momo_container_memory_rss{server=~\"$server\",name=~\"$container\",name=~\".+\"}) by (server, name)",
       "legendFormat": "{{name}} – {{server}}"
      }
     ]
    },
    {
     "title": "Memory Cached",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(momo_container_memory_cache{server=~\"$server\",name=~\"$container\",name=~\".+\"}) by (server, name)",
       "legendFormat": "{{name}} – {{server}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network / Block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Sent/Receive Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(momo_container_network_transmit_bytes_total{server=~\"$server\",name=~\"$container\",name=~\".+\"}[5m])) by (server, name)",
     "legendFormat": "{{name}} – {{server}} (tx)"
    },
    {
     "expr": "sum(rate(momo_container_network_receive_bytes_total{server=~\"$server\",name=~\"$container\",name=~\".+\"}[5m])) by (server, name) * -1",
     "legendFormat": "{{name}} – {{server}} (rx)"
    }
   ]
  },
  {
   "title": "Block I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(momo_container_blkio_bytes_total{op=\"write\",server=~\"$server\",name=~\"$container\"}[5m])) by (server, name)",
     "legendFormat": "{{name}} – {{server}} (write)"
    },
    {
     "expr": "sum(rate(momo_container_blkio_bytes_total{op=\"read\",server=~\"$server\",name=~\"$container\"}[5m])) by (server, name) * -1\n",
     "legendFormat": "{{name}} – {{server}} (read)"
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "momo_container_info{server=~\"$server\",name=~\"$container\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}